export const RECEIVE_PROJECT = "RECEIVE_PROJECT";
export const SHOW_CREATE_MODAL = "SHOW_CREATE_MODAL";
export const HIDE_CREATE_MODAL = "HIDE_CREATE_MODAL";
export const CREATE_PROJECT_START = "CREATE_PROJECT_START";
export const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
export const CREATE_PROJECT_ERROR = "CREATE_PROJECT_ERROR";
 